name: comfyui_docker

services:
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile

    image: comfyui:latest
    container_name: comfyui

    ports:
      - "8188:8188"

    volumes:
      - ../workspace/comfyui:/app/ComfyUI
      - ../workspace/workflows:/app/ComfyUI/user/default/workflows
      - ../workspace/custom_nodes:/app/ComfyUI/custom_nodes
      - ../workspace/models:/models
      - ../workspace/input:/input
      - ../workspace/output:/output

    working_dir: /app/ComfyUI

    
    ############################## GPU SECTION ###########################################
    # Comment out NVIDIA and AMD entries for CPU
 

    # NVIDIA GPU - Keep this line commented out - uncomment below for nvidia settings
    gpus: all
    environment:
      - NVIDIA_VISIBLE_DEVICES=all


    # AMD / ROCm GPU - Keep this line commented out - uncomment below for nvidia settings
    # devices:
    #   - /dev/kfd:/dev/kfd
    #   - /dev/dri:/dev/dri


    ######################################################################################
    
    
    restart: unless-stopped

    command:
      - python
      - main.py
      - --listen
      - 0.0.0.0
      - --input-directory
      - /input
      - --output-directory
      - /output
